language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python bucketlist_django/manage_testing.py makemigrations
  - python bucketlist_django/manage_testing.py migrate
# command to run tests
script: coverage run --source='.' bucketlist_django/manage_testing.py test bucketlist
after_success: coveralls