language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install coveralls
- python bucketlist_django/manage_testing.py makemigrations
- python bucketlist_django/manage_testing.py migrate
script: coverage run --source='.' bucketlist_django/manage_testing.py test bucketlist
after_success: coveralls
deploy:
  provider: heroku
  api_key:
    secure: "C6f579CpCzeV84PpTtcLwUBq7j7M3HL39bc0+KviMlqMoF7UHCVEvvax6UIFVJcAV4u9FY83lngkCguiRST/BY0z59qaZs5CXUPdMVYXVuJqqaukwYmTWGgLFpOnDBdLEQ3ufpt38Bp4uWxx7fHT7DKweb/QIml4Kc3ppJTIKemS4n+bX+9rtO7eKN1PMZ2CT6m1bQBognSexjksWMRlBvptNBTmRJLpNsgfeirKGhXDcDpLCF2df3fJrmgbWY7IpuHY3CD83hnSEaa7Pc443rZSXmiJ1rSTi3Ct1/qaXKlx4n3QsTtTs05JPuKMHueK3nZza8zF1ZY6gyhSegWUF/7bulwAgam4CYd30HqLo6L1b4cIrIr5eFBXSxp/PniB5uMbnvMaAhCFGkdFkfISnrD1LTXMnrpLt7HOCYtm4bCmsZcGWkjS529LXSkMWLEXoJ0G5wpNyPsfxaJPhRhWNnh7Dvft/4dqf12O7Ys5/dUoOmYkgEf5YZIhsarwLQDaPuT+57blto9bj2X7AxSHsyyVU9iUZVW8u14cy4ATNTzuJuencc7Fs/apmeFgLsjh2D5GIO6fAK3xd3v84lmCtWZg24+RBNLmjjG241l3g13pft7UtEe3YbOccleglL7QbAk4ARjl1rYWxnGLepeWSZ4ioCsE2aZMga0iinLbeE8="
  app:
    master: django-bucketlist-application
  on: master
  run:
  - 'python bucketlist_django/manage_production.py collectstatic'
  - 'python bucketlist_django/manage_production.py makemigrations'
  - 'python bucketlist_django/manage_production.py migrate'
