language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install coveralls
- python bucketlist_django/manage_testing.py makemigrations
- python bucketlist_django/manage_testing.py migrate
script: coverage run --source='.' bucketlist_django/manage_testing.py test bucketlist
after_success: coveralls
deploy:
  provider: heroku
  api_key:
    secure: bPzAw1MnrE/0bZSBPbjEUsmBJDEVs0cYqTHEGPGe4da1lYd9kjaFL6hrb714K60ErUY6xO4be4vT1qNqm/PVQK1AU3pe52dkztvWFlFvAKkpO8/XvKPH4msmYaAGSYOa1dnMeIgbzRtvN/mGXSghuyodMZrOB9bqVBTuDGtQYRSlilKl1SilOCzI/0A4Jrbf6WnTL4MNZA7woHZg4KGjf0qJocbf1jeiif2pCzfRqn6uxSEqtL1sz/IAGSOh3gbUTSFYDo9YbS6KtqmzyDLtXHTkWMiN96fmFC4qfL6H2etOj8gqy6sosnesLHQ7fYW5xZDrj02IbQymoUiJLrlDF3MGPkEBITvaOFr19lUlTT5xPsJBejlj8Cl9PTYXXcNxwN5NaneZWfbMpzGjrbDKF6QnV8ndHSrZiD8vLmgZCCIy/B1L7TuwbV0eGFWMvEDfHIDEaNMnb0AxubhX17lwGXhcLGVRPOW83aHBd/BVsvk4XZSQX1aNDGkGxi7fa6hlkC0qnWfiILFBuoWMt0mlImpX3M7j6KZqd7K2Ynwh/xvKI2zbcq16d8kHbVeaSyG/YxmIaCRy8LyGAUjoz32HMOcAKFMmY5FOIbPcVSooUlUB70MDIyYr5VM1jex8sfy8TNiFDseYZfOLYbpf9n5UtPAYXRtG3/YmmWv8Gimj5UE=
  app: django-bucketlist-application
  on:
    repo: andela-tadesanya/django-bucketlist-application
    branch: master
  skip_cleanup: true
  